# Generated by Django 2.0 on 2018-04-23 13:47

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedrawApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='building',
            name='coordinates',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
    ]
