# Generated by Django 2.0 on 2018-04-05 20:45

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedrawApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), default=[None, None, None, None, None], size=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='ada',
            field=models.NullBooleanField(verbose_name='Americans with Disabilities Act Compliance'),
        ),
        migrations.AlterField(
            model_name='room',
            name='draw_rank',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='polygons',
            field=django.contrib.postgres.fields.jsonb.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='size_rank',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=5),
        ),
        migrations.AlterField(
            model_name='room',
            name='sub_free',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), size=20),
        ),
    ]
