# Generated by Django 2.0 on 2018-04-21 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedrawApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='name',
        ),
    ]
