# Generated by Django 2.0.3 on 2018-04-25 16:52

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedrawApp', '0002_auto_20180423_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='favorites',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='groups',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(null=True), null=True, size=5),
        ),
    ]
