# Generated by Django 2.0 on 2018-04-09 01:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RedrawApp', '0002_rankfloat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floor',
            name='floorplan',
        ),
        migrations.AddField(
            model_name='floor',
            name='dimeinsions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[10200, 6600], size=2),
            preserve_default=False,
        ),
    ]
