# Generated by Django 2.0 on 2018-04-09 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RedrawApp', '0003_auto_20180408_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floor',
            old_name='dimeinsions',
            new_name='dimensions',
        ),
    ]
