export default [
	{ value: 'Joline Hall', },
	{ value: 'Brown Hall', },
	{ value: 'Dod Hall', },
	{ value: 'Edwards Hall', },
	{ value: '1903 Hall', },
	{ value: 'Cuyler Hall', },
	{ value: 'Blair Hall', },
	{ value: 'Bogle Hall', },
	{ value: '1967 Hall', },
	{ value: 'Witherspoon Hall', },
	{ value: 'Yoseloff Hall', },
	{ value: 'Hamilton Hall', },
	{ value: '1915 Hall', },
	{ value: 'Scully Hall', },
	{ value: 'Lauritzen Hall', },
	{ value: 'Bloomberg Hall', },
	{ value: 'Wright Hall', },
	{ value: 'Buyers Hall', },
	{ value: 'Baker Hall E', },
	{ value: 'Forbes College Main', },
	{ value: 'Fisher Hall', },
	{ value: 'Wendell Hall Building C', },
	{ value: 'Holder Hall', },
	{ value: 'Murley-Pivirotto Family Tower', },
	{ value: 'Lockhart Hall', },
	{ value: 'Little Hall', },
	{ value: 'Campbell Hall', },
	{ value: 'Dickinson Street 2', },
	{ value: 'Feinberg Hall', },
	{ value: 'Foulke Hall', },
	{ value: 'Henry Hall', },
	{ value: 'Class of 1901-Laughlin Hall', },
	{ value: 'Walker Hall', },
	{ value: 'Hargadon Hall', },
	{ value: '1927-Clapp Hall', },
	{ value: 'Baker Hall S', },
	{ value: '1981 Hall', },
	{ value: 'Wendell Hall Building B', },
	{ value: 'Patton Hall', },
	{ value: 'Wilf Hall', },
	{ value: 'Forbes Addition', },
	{ value: 'Spelman Halls', },
	{ value: 'Wilcox Hall', },
	{ value: '1976 Hall', },
	{ value: 'Gauss Hall', },
	{ value: 'Dodge-Osborn Hall', },
	{ value: '1939 Hall', },
	{ value: '1938 Hall', },
	{ value: '1937 Hall', },
];